### ISSUE TITLE
Colorize?

### ISSUE THREAD

**Issue by muschem** [astryzia/BashScan#17]
Probably low on the priority list, but maybe consider colorizing output at some point, for terminals that support it? Happy to help with the effort, but you probably don't want me picking colors, since I'm red/green colorblind :)

**Comment by astryzia** [comment]
Colorizing outputs is a great idea. Readability is pretty bad in its current state. I'll take care of working on this :)

**Comment by astryzia** [comment]
basic colorization/stylization added :) may not be complete but is a start!
