### ISSUE TITLE
Add --open flag

### ISSUE THREAD

**Issue by astryzia** [astryzia/BashScan#23]
Flag/parameter needed to display only hosts with open ports

**Comment by muschem** [comment]
This is a good idea, and should be pretty easy to implement

**Comment by muschem** [comment]
Should the flag apply to both stdout as well as file output, or did you have in mind for it to only suppress output for one or the other?

**Comment by muschem** [comment]
Solution offerred in PR #24 - approach I went with was consistent suppression for both stdout and files. If you want the file output to include live hosts with no open ports, we can just remove the file output if block from the new if test.

**Comment by astryzia** [comment]
I was going to suggest exactly as you did it, thank you!
